### ISSUE TITLE
"Wifi Server Mode" causes crash

### ISSUE THREAD

**Issue by morsik** [aramg/droidcam#30]
Android app connects to it - but nothing happens - black screen - and after like half minute it just segfaults.
Unfortunately backtrace is very incomplete for some strange reason… I installed all debug symbols, and even recompiled droidcam client with `-ggdb3` to include debug symbols but this is all I get:

```
 $ gdb ./droidcam 
GNU gdb (GDB) Fedora 8.3.50.20190824-30.fc31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./droidcam...
(gdb) r
Starting program: /home/morsik/Projects/third-party/droidcam/linux/droidcam 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
Device: Integrated_Webcam_HD: Integrate
Device: Integrated_Webcam_HD: Integrate
Device: Droidcam
Found driver: /dev/video2 (fd:5)
[New Thread 0x7fffe915a700 (LWP 55804)]
waiting on port 4747..got socket 7

Thread 2 "droidcam" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe915a700 (LWP 55804)]
0x00007ffff7079b28 in __libc_recv (fd=<optimized out>, buf=<optimized out>, len=<optimized out>, flags=<optimized out>) at ../sysdeps/unix/sysv/linux/recv.c:28
28	  return SYSCALL_CANCEL (recvfrom, fd, buf, len, flags, NULL, NULL);
(gdb) bt
#0  0x00007ffff7079b28 in __libc_recv (fd=<optimized out>, buf=<optimized out>, len=<optimized out>, flags=<optimized out>) at ../sysdeps/unix/sysv/linux/recv.c:28
#1  0x0ddfab275ee1bffe in  ()
#2  0xb13ee4e0b2e6e24b in  ()
#3  0xe9076547554f822a in  ()
#4  0x36be04d5bf57afc0 in  ()
#5  0xea86bc0d352677b1 in  ()
#6  0x34fc8357fa3907a3 in  ()
#7  0x0bb65fa8b98e3abd in  ()
#8  0xee1ccec0b9931c49 in  ()
#9  0xd0a9c3d3794dfd3d in  ()
#10 0x38eb941d1bfe36a9 in  ()
#11 0xff17f8dedc528456 in  ()
#12 0x91334942da4f1300 in  ()
#13 0xbec67fee3ed96e04 in  ()
#14 0x3c41351d9a9dd4cb in  ()
#15 0xff390e4ef781bc48 in  ()
#16 0x4ad900ffe22b3d00 in  ()
#17 0xfd56ee52bdc5cf78 in  ()
#18 0xd92a19d793e016dc in  ()
#19 0x774f11ef0beb2bfd in  ()
#20 0xc30a8fc60643d8ad in  ()
#21 0xedf5be9e03e4c170 in  ()
#22 0xa6d2be6a1822b6f0 in  ()
#23 0x95444c2d7ce231d6 in  ()
#24 0xeff76c9200ff7b2a in  ()
#25 0x466926026d9b5908 in  ()
#26 0x3d7e7c9f9c5c181b in  ()
#27 0x033fe92dbe8befea in  ()
#28 0x31a6d733be6a1d3e in  ()
#29 0x3cb85197b11a3ee9 in  ()
#30 0xc7acbe08318c656e in  ()
#31 0x54f0ce0a98f7070a in  ()
#32 0x10921acf46a54b52 in  ()
#33 0x055fe9eb01e0e477 in  ()
#34 0x1f7833b57fc1c17f in  ()
#35 0x22d7e917fe86afe0 in  ()
#36 0x11492d754a14df2b in  ()
#37 0x470f2b11b97016f9 in  ()
#38 0xf363a25fc1fa6e94 in  ()
#39 0xeebd536934bc382a in  ()
#40 0xad2b17867ceed69e in  ()
#41 0xa3356b6d952aa985 in  ()
#42 0x37da00ff697f333f in  ()
#43 0xc68f78373ea6fd5a in  ()
#44 0x8f17c44b6de6f49a in  ()
#45 0x2e91e8145212e072 in  ()
#46 0xbca2e8515420227a in  ()
#47 0x0d5ecf6ef2ed1bee in  ()
#48 0xf77a3d39dcbdb850 in  ()
#49 0xf51e3ce76be3d2a2 in  ()
#50 0xc7adb5260ab9afcc in  ()
#51 0xd23f00ffc1bd2c97 in  ()
#52 0x5185762ebfc481a7 in  ()
#53 0x7768e499ac793d8e in  ()
#54 0xea9657f3f871f01c in  ()
#55 0x001841f97765523b in  ()
#56 0x97769be45ea435e7 in  ()
#57 0x8740492e99dba68b in  ()
#58 0x57c4f78a9a733a2a in  ()
#59 0x771b60df259b205e in  ()
#60 0x33eb1221b3da6137 in  ()
#61 0x747fea3e4e0cf779 in  ()
#62 0x74a0905348abad76 in  ()
#63 0xc06c4310a42e4def in  ()
#64 0x30914e5f51719264 in  ()
#65 0x52d4539b8adb9300 in  ()
#66 0x54ad1f7b0b426406 in  ()
#67 0xdf13f3934c921682 in  ()
#68 0x096944b03bc5f9b7 in  ()
#69 0x965a00ff3ea9977f in  ()
#70 0xa615c6d0e9ec9f3b in  ()
#71 0xb3d4fa3f90116024 in  ()
#72 0xa7f5cf6d85942dce in  ()
#73 0xe99bb9cdc88c4158 in  ()
#74 0xd99f8b3d6adaa6de in  ()
#75 0xf4863926d7db64cb in  ()
#76 0x7bfd18c36fcf483d in  ()
#77 0xc693246eb461abd5 in  ()
#78 0x13e2a2923e153930 in  ()
#79 0x306e11cd3737ec6c in  ()
#80 0xaaf4b83e80439ffe in  ()
#81 0x1fe44170430e47e2 in  ()
#82 0x4fb2097611f24263 in  ()
#83 0xaab38d3dded96aa5 in  ()
#84 0xfcf4449fc3551e92 in  ()
#85 0xbf9846d67b4c3f78 in  ()
#86 0x00c0666619239969 in  ()
#87 0x6fee424d02ec6a70 in  ()
#88 0xe2c68883c3253922 in  ()
#89 0xe7314ee1c71938a3 in  ()
#90 0x8da526ca5cd4b17c in  ()
#91 0x6fadb5d2a7d71bee in  ()
#92 0xbdb90618c7fc1af1 in  ()
#93 0x55f032321ca504ed in  ()
#94 0x80fa85f52afd2087 in  ()
#95 0xa0353814756020d9 in  ()
#96 0x0dc316a11a4c9d79 in  ()
#97 0x149e75c5f36f0fdc in  ()
#98 0xbc06cf790794bcd6 in  ()
#99 0x3a1d86cfece7edcf in  ()
#100 0x19921cb6bef0de0a in  ()
#101 0x342935835ebf0378 in  ()
#102 0xf6df12fc2fe8c7c2 in  ()
#103 0x7b3a8dc7bfb33fc0 in  ()
#104 0xa967b1d4c1fee6d9 in  ()
#105 0xce01cbc8853987c6 in  ()
#106 0x3577dcce7118904a in  ()
#107 0x1e2fbcd0b56074fb in  ()
#108 0x78a90c6d6fcea6ab in  ()
#109 0x218b651badaeac8e in  ()
#110 0xfc1523e7fbc0101c in  ()
#111 0x46dea7efc41b78c5 in  ()
#112 0xb45ff160e41072ea in  ()
#113 0x2dbe49db7f47f01f in  ()
#114 0xcf33ade6e19b1f7c in  ()
#115 0x65333296bc90e8a9 in  ()
#116 0x43caaf5ffe70dd9e in  ()
#117 0x515d81812a039e63 in  ()
#118 0x5f77d555ab7beaa6 in  ()
#119 0xadb969dc1a3f0ff0 in  ()
#120 0xb7f5b1dfa74fded6 in  ()
#121 0xeace06f145243dc5 in  ()
#122 0xff4badd56e2d0236 in  ()
#123 0x8c10f88f908fb500 in  ()
#124 0xf0ddfe565ff8a2d7 in  ()
#125 0x1f1788e6e1d99de5 in  ()
#126 0x57f891033f8c7edd in  ()
#127 0x1455f823feca6b9f in  ()
#128 0x1c6ec21974db47a8 in  ()
#129 0xbfba864d3f700a95 in  ()
#130 0x9f48f7e9de9a7a86 in  ()
#131 0x25bb1e886a9fccea in  ()
#132 0xf00a3f2e4600ff1b in  ()
#133 0xe33efde2acd349a5 in  ()
#134 0x1dad506a8dd729e8 in  ()
#135 0xd9ff9ffa8300ff9a in  ()
#136 0x0000000000000000 in  ()
```

This is VERY strange…

**Comment by morsik** [comment]
Confirmed it's working correctly now.
